### ISSUE TITLE
What Visual Studio theme is in the screenshot?

### ISSUE THREAD

**Issue by mejobloggs-cw** [jiripolasek/EditorBar#6]
https://github.com/jiripolasek/EditorBar/blob/master/assets/screenshot.png

Looks super nice, what theme? I want to try it :)

Thanks

**Comment by jiripolasek** [comment]
Hello,

that is one of the new "tinted" themes for refreshed Visual Studio UI Refresh. You'll need a Visual Studio 2022 Preview (17.9.0 Preview 1.0+) and enable new control styles in experimental features in options. Then the new themes will be available along side the original light/dark themes.

https://devblogs.microsoft.com/visualstudio/the-visual-studio-ui-refresh-preview-is-here/
